catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),

]

locallibrary/catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [

]

locallibrary/locallibrary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView #redirecionamento raiz

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')), #incluindo caminho da URL da aplicação
    path('', RedirectView.as_view(url='/catalog/')), #página principal (home)

]

locallibrary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView #redirecionamento raiz

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')), #incluindo caminho da URL da aplicação
    path('', RedirectView.as_view(url='/catalog/')), #página principal (home)
]

catalog/models.py
from django.db import models
from django.urls import reverse
from shortuuid.django_fields import ShortUUIDField

# Create your models here.
class MyModelName(models.Model):
    myFieldName = models.CharField(max_length=20, help_text='Primeiro Nome')

    class Meta:
        ordering = ['myFieldName'] #ordenação dos dados por nome

    def get_absolute_url(self):
        """Retorna a url para acessar uma instancia específica de MyModelName."""
        return reverse('model-detail-view', args=[str(self.id)])

    def __str__(self):
        """String para representar o objeto MyModelName (no site Admin)."""
        return self.myFieldName

class Genero(models.Model):
    """Modelo que representa o genero do livro."""
    nome = models.CharField(max_length=200, help_text='Digite o genero do livro (Ex: Ficção Científica)')

    def __str__(self):
        """String for representing the Model object."""
        return self.nome
    
class Book(models.Model):
    titulo = models.TextField('Titulo', max_length=200, help_text='Digite o título do livro')
    #tipo primitivo que permite estar vinculado a vários objetos
    #Com o 'on_delete=models.SET_NULL, null=True' conseguimos manter 
    #a integridade da referencia dos dados
    autor = models.ForeignKey('Autor', on_delete=models.SET_NULL, null=True, help_text='Digite o autor do livro')
    resumo = models.TextField('Resumo', max_length=1000, help_text='Digite o resumo do livro')
    isbn = models.CharField('ISBN', max_length=13, help_text='Número ISBN do livro')
    #um genero pode ter mais de um livro
    #um livro pode ter mais de um genero
    genero = models.ManyToManyField(Genero, help_text='Digite o gênero do livro')
    def display_genero(self):
        return ', '.join(genero.nome for genero in self.genero.all()[:3])
    display_genero.short_descrition = "Gênero"

    def __str__(self):
        return self.titulo
    
    def get_absolute_url(self):
        """Retorna a url para acessar os detalhes gravados na instancia da classe Book"""
        return reverse('detalhe-do-livro', args=[str(self.id)])

class BookInstance(models.Model):
    #id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    id = ShortUUIDField(
        length=5,
        max_length=8,
        prefix="id_",
        alphabet="abcdefg1234",
        primary_key=True,
    )
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True, help_text='')
    dataDeDevolucao = models.DateField(null=False, blank=True)

    imprint = models.CharField(max_length=300, null=True)

    LOAN_STATUS=(
        ('m', 'Em manutenção'),
        ('e', 'Emprestado'),
        ('d', 'Disponível'),
        ('r', 'Reservado'), 
    )

    status = models.CharField(
        max_length=1,
        choices = LOAN_STATUS,
        blank=True,
        default='m',
        help_text = 'Disponibilidade do livro', 
    )

    class Meta:
        ordering = ['dataDeDevolucao']

    def __str__(self):
        #string que representa uma instancia do modelo
        return f'{self.id} ({self.book.titulo})'

class Autor(models.Model):
    nome = models.CharField('Nome', max_length=100)
    sobrenome = models.CharField('Sobrenome', max_length=100)
    #blank=True indica que o campo pode ficar em branco
    dataDeNascimento = models.DateField('Data de Nascimento',null=True, blank=True)
    dataDeMorte = models.DateField('Data de Morte',null=True, blank=True)
    # outros campos e métodos
    class Meta:
        ordering = ['sobrenome', 'nome'] #ordenação dos dados por sobrenome e nome do autor

    def get_absolute_url(self):
        """Retorna a url para acessar os detalhes gravados na instancia da classe Book"""
        return reverse('informações-do-autor', args=[str(self.id)])

    def __str__(self):
        return '{}, {}'.format(self.sobrenome, self.nome)

locallibrary/catalog/models.py
from django.db import models
from django.urls import reverse
import uuid

# Create your models here.
class MyModelName(models.Model):
    myFieldName = models.CharField(max_length=20, help_text='Primeiro Nome')

class Meta:
    ordering = ['-myFieldName'] #ordenação dos dados por nome

    def get_absolute_url(self):
        """Retorna a url para acessar uma instancia específica de MyModelName."""
        return reverse('model-detail-view', args=[str(self.id)])

    def __str__(self):
        """String para representar o objeto MyModelName (no site Admin)."""
        return self.myFieldName

class Genre(models.Model):
    """Modelo que representa o genero do livro."""
    name = models.CharField(max_length=200, help_text='Digite o genero do livro (Ex: Ficção Científica)')

    def __str__(self):
        """String for representing the Model object."""
        return self.name
    
class Book(models.Model):
    titulo = models.TextField('Titulo', max_length=200, help_text='Digite o título do livro')
    #tipo primitivo que permite estar vinculado a vários objetos
    autor = models.ForeignKey('Autor', null=False, help_text='Digite o autor do livro')
    resumo = models.TextField('Resumo', max_length=1000, help_text='Digite o resumo do livro')
    isbn = models.CharField('ISBN', max_length=13, help_text='Número ISBN do livro')
    #um genero pode ter mais de um livro
    #um livro pode ter mais de um genero
    genero = models.ManyToManyField(Genre, help_text='Digite o gênero do livro')

    def __str__(self):
        return self.titulo
    
    def get_absolute_url(self):
        """Retorna a url para acessar os detalhes gravados na instancia da classe Book"""
        return reverse('detalhe-do-livro', args=[str(self.id)])

class BookInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    book = models.ForeignKey('Book', null=False, help_text='')
    dataDeDevolucao = models.DateField(null=False, blank=True)

    LOAN_STATUS=(
        ('m', 'Em manutenção'),
        ('e', 'Emprestado'),
        ('d', 'Disponível'),
        ('r', 'Reservado'), 
    )

    status = models.CharField(
        max_length=1,
        choices = LOAN_STATUS,
        blank=True,
        default='m',
        help_text = 'Disponibilidade do livro', 
    )

    class Meta:
        ordering = ['-dataDeDevolucao']

    def __str__(self):
        #string que representa uma instancia do modelo
        return f'{self.id} ({self.book.titulo})'

catalog/views.py
from django.shortcuts import render
from catalog.models import Autor, Book, BookInstance, Genero
from django.views import generic

class BookListView(generic.ListView):
    model = Book
    context_object_name = 'my_book_list'
    queryset = Book.objects.filter(titulo__icontains='dados') # Get 5 books containing the title war
    template_name = 'templates/listaDelivros.html'

    def get_queryset(self):
        return Book.objects.filter(titulo__icontains='dados') # Get 5 books containing the title war
    
    def get_context_data(self, **argumento):
        # Call the base implementation first to get the context
        context = super(BookListView, self).get_context_data(**argumento)
        # Create any data and add it to the context
        context['some_data'] = 'This is just some data'
        return context


# Create your views here.
def index(request):

    numeroDeLivros = Book.objects.all().count() #contar o número de livros
    numeroDeCopias = BookInstance.objects.all().count() #contar o número de instancias dos livros
    numeroDeAutores = Autor.objects.count()#contar o número de autores
    generos = Genero.objects.count() #quantidade de generos cadastrados
    contarLivrosKeyword = Book.objects.filter(titulo__icontains='dados').count()

    context = {
        'Número de livros': numeroDeLivros,
        'Número de cópias': numeroDeCopias,
        'Número de Autores': numeroDeAutores,
        'Generos': generos,
        'Livros com a palavra_chave': contarLivrosKeyword,
    }

    return render(request, 'index.html', context=context)

locallibrary/catalog/views.py
from django.shortcuts import render

# Create your views here.

catalog/templates/baseGenerica.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}<title>Biblioteca Local</title>{% endblock %}
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous" />
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />

    {% load static %}
    <img src="{% static 'imagens/biblioteca_local.jpg' %}" alt="Biblioteca Senac" style="width:555px;height:540px;" />

    <!--Essa tag url aceita o nome de uma função path() chamado em urls.py e os valores para quaisquer argumentos que 
        a view associada receberá dessa função e retorna um URL que você pode usar para vincular ao recurso.-->
    <li><a href="{% url 'index' %}">Home</a></li>
    <li><a href="{% url 'books' %}">Livros</a></li> <!--caminho no path('books/'-->
    <li><a href="{% url 'index' %}">Autores</a></li>

</head>

<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-2">
                {% block sidebar %}
                <ul class="sidebar-nav">
                    <li><a href="">Livros</a></li>
                    <li><a href="">Autores</a></li>
                </ul>
                {% endblock %}
            </div>
            <div class="col-sm-10">{% block content %}{% endblock %}</div>
        </div>
    </div>
</body>

</html>

catalog/templates/index.html
{% extends 'baseGenerica.html' %} <!--Herança-->
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}
    <title>Biblioteca Local</title>
    {% endblock %}
</head>

<body>
    {% block sidebar %}
    <!---->
    {% endblock %}

    {% block content %}
    <h1>Home da nossa Biblioteca Local</h1>
    <p>Bem vindo a Biblioteca Local, um website desenvolvido por <a
            href="https://developer.mozilla.org/pt-BR/docs/Learn/Server-side/Django/Tutorial_local_library_website">Mozila
            Developer Network</a></p>
    <p>Nossa livraria tem: </p>
    <ul>
        <li><strong>Quantidade de Livros: </strong> {{ numeroDeLivros }}</li>
        <li><strong>Quantidade de Copias: </strong> {{ numeroDeCopias }}</li>
        <li><strong>Número de autores: </strong> {{ numeroDeAutores }}</li>
        <li><strong>Número de generos: </strong> {{ generos }}</li>
        <li><strong>Livros com a palavra-chave: dados: </strong> {{ contarLivrosKeyword }}</li>
    </ul>
    {% endblock %}
</body>

</html>

catalog/templates/listaDelivros.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Book List</h1>
{% if book_list %}
<ul>
    {% for book in book_list %}
    <li>
        <a href="{{ book.get_absolute_url }}">{{ book.titulo }}</a> ({{book.autor}})
    </li>
    {% endfor %}
</ul>
{% else %}
<p>Livro não encontrado</p>
{% endif %}
{% endblock %}